# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-04 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BinaryFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_binary', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='BooleanFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_boolean', models.BooleanField(default=False)),
                ('field_null_boolean', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CommonOptionBlank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_blank', models.TextField(blank=True)),
                ('field_not_blank', models.TextField()),
                ('field_int_blank', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CommonOptionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_choice', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], db_column='sex', default='m', help_text='sex of this entry', max_length=1, verbose_name='the sex')),
            ],
        ),
        migrations.CreateModel(
            name='CommonOptionDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_integer', models.IntegerField(default=5)),
                ('field_char', models.CharField(default='unknown', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CommonOptionIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_index', models.CharField(db_index=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CommonOptionNull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_null', models.IntegerField(null=True)),
                ('field_not_null', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommonOptionUnique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_unique', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FloatFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_float', models.FloatField(default=0.0)),
                ('field_decimal', models.DecimalField(decimal_places=2, default=0.12454646, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='IntegerFileds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_integer', models.IntegerField()),
                ('field_positive_small_integer', models.PositiveSmallIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='StringFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_char', models.CharField(max_length=5)),
                ('field_text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_date', models.DateField(auto_now=True)),
                ('field_datetime', models.DateTimeField(auto_now_add=True)),
                ('field_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
