

env = Environment(SHLIBPREFIX = '')
env.AppendUnique(CPPPATH = ['/usr/local/include/luajit-2.0'])
app = env.SharedLibrary('app',
                     'app.c',
                     CFLAGS=['-g', '-O2', '-Wno-deprecated', '-Wall'],
                     LINKFLAGS = ['-fPIC'],
                     LIBS = ['dl'])

env.Install('/usr/local/lib/lua/5.1', app)
env.Alias('install', '/usr/local/lib/lua/5.1')
