
import os

env = Environment()

cppPath = [
    os.path.realpath('../../../../third/lua-5.3.4/include'),
    os.path.realpath('../../../../third/googletest-1.8.0/include')
]

libPath = [
    os.path.realpath('../../../../third/lua-5.3.4/lib/mac'),
    os.path.realpath('../../../../third/googletest-1.8.0/lib/mac')
]

env.AppendUnique(CPPFLAGS=['-g', '-O2', '-Wno-deprecated', '-Wall'],
                 CPPPATH = cppPath,
                 LIBPATH = libPath,
                 LIBS = ['lua', 'gmock'])

#env.Program('intepreter', 'intepreter.c')

env.Program('test', ['main.cpp', 'stack_test.cpp'])

